# pubspec.yaml
name: bubuy_lovers
description: Aplikasi berita hewan Bubuy Lovers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5          # Untuk state management
  shared_preferences: ^2.2.3 # Untuk menyimpan data lokal
  image_picker: ^1.1.2      # Untuk memilih gambar dari galeri/kamera

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bubuy.png # Pastikan file ini ada